(library
 (name data_service_rpc)
 (modules data_service_rpc latest_result)
 (libraries core async)
 (preprocess
  (pps ppx_jane)))

(library
 (name data_service)
 (modules (:standard \ data_service_rpc latest_result))
 (libraries core async cohttp-async uri yojson data_service_rpc)
 (preprocess
  (pps ppx_jane ppx_yojson_conv)))
