(library
 (name data_service_rpc)
 (modules data_service_rpc)
 (libraries core async)
 (preprocess
  (pps ppx_jane)))

(library
 (name data_service)
 (modules gbfs citi_bike data_service)
 (libraries core async cohttp-async uri yojson data_service_rpc)
 (preprocess
  (pps ppx_jane ppx_yojson_conv)))

(executable
 (name main)
 (modules main)
 (libraries core async data_service))
